[project]
name = "CuBATS"
version = "1.0.1"
description = "Computer vision-Based Antigen Target Selector"
authors = [
    { name = "Moritz Dinser", email = "moritz.dinser@hnu.de" },
    { name = "Daniel Hieber", email = "daniel.hieber@hnu.de" },
]

dependencies = [
    "openslide-python>=1.3",
    "valis-wsi>=1.0",
    "onnx>=1.16",
    "onnx2torch==1.5",
    "torchvision>=0.20",
    "torchstain>=1.3",
    "numpy>=1.26.4,<2.0",
    "array-api-compat>=1.11.2",
    "onnxruntime-gpu>=1.10; sys_platform == 'win32'",
    "cupy-cuda12x>=13.3; sys_platform == 'win32'",
    "openslide-bin>=4.0.1.2",
]

requires-python = ">=3.10,<3.13"
readme = "README.md"
license = { text = "MIT" }
keywords = ["digital pathology", "whole-slide imaging", "patient-specific antigen analysis", "spatial antigen heterogeneity", ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Bio-Informatics"]

[project.urls]
Repository = "https://github.com/hnu-digihealth/CuBATS"
Documentation = "https://hnu-digihealth.github.io/CuBATS/"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.scripts]
test = "pdm run -v pytest tests"
lint = "pdm run -v flake8 --ignore=E124,E127,E128,E203,E701,E731,W503 --max-line-length 120 src tests"
sort = "pdm run -v isort --check-only src tests"
apply_sort = "pdm run -v isort src tests"
cov_report = { shell = "pdm run -v coverage run -m pytest tests && pdm run coverage xml && pdm run coverage report" }
check_pre_commit = "pdm run pre-commit run --all-files"
# run prior to tests
pre_test = "pdm install"
build-docs = { shell = '''
cd docs
make clean
make html
OS_NAME=$(uname)
if [ "$OS_NAME" = "Darwin" ]; then
    open build/html/index.html
elif [ "${OS_NAME:0:5}" = "Linux" ]; then
    xdg-open build/html/index.html
elif [[ "${OS_NAME:0:10}" = "MINGW32_NT" ]] || [[ "${OS_NAME:0:10}" = "MINGW64_NT" ]]; then
    start build/html/index.html
fi
''' }


[tool.isort]
src_paths = ["src", "tests"]
known_first_party = "cubats"
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
import_heading_firstparty = "CuBATS"

[dependency-groups]
dev = [
    "pre-commit>=3.7.0",
    "notebook>=7.1.3",
    "isort>=5.13.2",
    "wheel>=0.45.1",
    "ipykernel>=6.29.5",
    "twine>=6.2.0",
]
testing = [
    "pytest>=8.2.0",
    "coverage>=7.5.0",
    "flake8>=7.0.0",
    "pylint>=3.2.7",
    "graphviz>=0.20.3",
    "imagecodecs>=2024.6.1",
]
docs = [
    "sphinx>=7.3",
    "sphinx-rtd-theme>=2.0",
]
