name: development testing

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  workflow_dispatch:

jobs:
  isort:
    runs-on: ubuntu-latest
    name: Import Order
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pdm sync -d
      - name: isort Lint
        run: |
          pdm sort

  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pdm sync -d
      - name: flake8 Lint
        run: |
          pdm lint

  testing:
    name: Test
    needs: [flake8-lint, isort]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install system libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libvips-dev libopenslide0
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.12'
    - name: Run Tests
      run: |
        pdm test
